paths:
  /api/products/test/mockingProducts:
    get:
      summary: This is a mocking of products. 
      tags:
        - Products
      responses:
        "200":
          description: Products mocking ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/ProductMocked'
        "500":
          description: Internal server error.      
  /api/products:
    get:
      summary: This service lists all the products of the ecommerce.
      tags:
        - Products
      responses:
        "200":
          description: Products listed ok from database.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Internal server error.
  /api/products/{id}:
    get:
      summary: This service lists a product of the ecommerce.
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: Product id.
          schema:
            $type: String
      responses:
        "200":
          description: Product listed ok.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Server internal error.
    put:
      summary: Updates the product.
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: Product id.
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: Product updated.
        "404":
          description: Product not found.
        "500":
          description: Internal server error.
components:
  schemas:
    Product:
      type: Object
      properties:
        _id:
          type: ObjectId
          description: Product Id generated by mongodb.
        title:
          type: String
          description: Product title.
        description:
          type: String
          description: Product description.
        price:
          type: Number
          description: Product Price.
        thumbnail:
          type: String
          description: Product thumbnail.
        code:
          type: String
          description: Internal product code.
        stock:
          type: Number
          description: Product Stock.
      example:
        _id: ObjectId("654fefc59c5bdc60a07bfc6f")
        title: Shoes
        description: Trainning Shoes from Japan.
        price: 200
        thumbnail: http://urlropa1.jpg
        code: Xd9ofa
        stock: 10  
    ProductMocked:
      type: Object
      properties:
        title:
          type: String
          description: Product title.
        descripcion:
          type: String
          description: Product description.
        price:
          type: Number
          description: Product Price.
        thumbnail:
          type: String
          description: Product thumbnail.
        code:
          type: String
          description: Internal product code.
        stock:
          type: Number
          description: Product Stock.
      example:
        title: Shoes
        description: Trainning Shoes from Japan.
        price: 200
        thumbnail: http://urlropa1.jpg
        code: Xd9ofa
        stock: 10
  requestBodies:
    updateProduct:
      type: Object
      properties:
        title:
          type: String
          description: Product title.
        descripcion:
          type: String
          description: Product description.
        price:
          type: Number
          description: Product Price.
        thumbnail:
          type: String
          description: Product thumbnail.
        code:
          type: String
          description: Internal product code.
        stock:
          type: Number
          description: Product Stock.
      example:
        title: Shoes
        description: Trainning Shoes from Japan.
        price: 200
        thumbnail: http://urlropa1.jpg
        code: Xd9ofa
        stock: 10
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT